services:
  postgres:
    container_name: whatdoing_pg_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - "./.database/pgdata:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    # networks:
    #   - whatdoing-server
